### ISSUE TITLE
Message	"Object reference not set to an instance of an object."	string

### ISSUE THREAD

**Issue by zxxc** [jacek-gorgon/NJsonApi#30]
`at NJsonApi.Serialization.TransformationHelper.CreateRelationships(Object objectGraph, String parentId, IResourceMapping resourceMapping, Context context)
   at NJsonApi.Serialization.TransformationHelper.CreateResourceRepresentation(Object objectGraph, IResourceMapping resourceMapping, Context context)
   at NJsonApi.Serialization.JsonApiTransformer.<>c__DisplayClass8_0.<Transform>b__0(Object o)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at NJsonApi.Serialization.TransformationHelper.ChooseProperResourceRepresentation(Object resource, IEnumerable`1 representationList)
   at NJsonApi.Serialization.JsonApiTransformer.Transform(Object objectGraph, Context context)
   at JsonApiHelpers.Formatters.EnhancedJsonApiFormatter.WriteToStream(Type type, Object value, Stream writeStream, HttpContent content) in C:\\JsonApiHelpers\Formatters\EnhancedJsonApiFormatter.cs:line 53
   at System.Net.Http.Formatting.BufferedMediaTypeFormatter.WriteToStream(Type type, Object value, Stream writeStream, HttpContent content, CancellationToken cancellationToken)
   at System.Net.Http.Formatting.BufferedMediaTypeFormatter.WriteToStreamSync(Type type, Object value, Stream writeStream, HttpContent content, CancellationToken cancellationToken)
   at System.Net.Http.Formatting.BufferedMediaTypeFormatter.WriteToStreamAsync(Type type, Object value, Stream writeStream, HttpContent content, TransportContext transportContext, CancellationToken cancellationToken)`

What is the reason of this exception?

**Comment by brainwipe** [comment]
Hi there, thanks for getting in touch. Can you post your resource model code please?

**Comment by zxxc** [comment]
Hi. we found that i used WithLinkedResource instead of WithSimpleProperty
Resource was registred. It simple object with two properties.
Issue for me fixed. But receiving NRE is not helping to undrstand what is going on
You can close issue
