### ISSUE TITLE
Class with a property that does not have a set causes crash on startup

### ISSUE THREAD

**Issue by BenHerron** [jacek-gorgon/NJsonApi#9]
Class with a property that does not have a set 

```
public class Test
{
    public int Id { get; set; }
    public DateTime? VerifiedUtc { get; set; }

    // Causes crash in library
    public bool IsVerified { get { return (VerifiedUtc != null); } }
}
```

Causes crash on the following lines when starting up.

```
configBuilder
    .Resource<Test>()
    .WithAllProperties()
    .WithLinkTemplate("/tests/{id}");

An exception of type 'System.ArgumentNullException' occurred in System.Core.dll but was not handled in user code

Value cannot be null. Parameter name: method

at System.Linq.Expressions.Expression.Call(Expression instance, MethodInfo method, IEnumerable`1 arguments)
at NJsonApi.ResourceConfigurationBuilder`1.AddProperty(PropertyInfo propertyInfo, Type type, SerializationDirection direction)
at NJsonApi.ResourceConfigurationBuilder`1.WithAllSimpleProperties()
at NJsonApi.ResourceConfigurationBuilder`1.WithAllProperties()
```

I can understand not supporting it, but would be great to have a clear error message with property name and why, to make debugging easier.

**Comment by jacek-gorgon** [comment]
Agreed, this needs to be handled better. Also, currently only expressions pointing at actual properties are supported and it might be beneficial to let consumers specify _any_ get/set lambdas. It's part of polishing I plan to apply anyway.
